### ISSUE TITLE
What is the proper use of the `categorical_columns` parameter in the constructor?

### ISSUE THREAD

**Issue by omaralvarez** [zhao-zilong/Tabula#2]
After using your code a couple of times, a question has popped up in my mind, what is the proper use of `categorical_columns` in the Tabula constructor:

``` python
categorical_columns: list = [],
```

The doubt comes from the fact that since we are dealing with LLMs, I don't understand why encoding categories is needed. Intuitively you would think that for an LLM it would be more difficult to deal with category encondings instead of names.

So my question is, is it better to give Tabula the categorical column list or not?

**Comment by zhao-zilong** [comment]
Hi @omaralvarez ,

The reason I added this function is because I want to first transfer each category into one integer. Then during the tokenization step, it is easier to tokenize each category to only one token. That helps to make the token sequence shorter. You can leave the categorical_columns as empty if you don't need this feature.

**Comment by omaralvarez** [comment]
Thanks for the answer, so if I understand correctly, it is a matter of just reducing token length and if that is not a problem you can keep it empty?

**Comment by zhao-zilong** [comment]
Hi @omaralvarez 
Yes, your understanding is correct. I add it just because in my paper, I mentioned that user can transform their category to shorter and simpler text so that it can be tokenized one token. With this function, user does not need to do that manually. It will first encode each category to an interger then encode as one token.

**Comment by omaralvarez** [comment]
Perfect, thank you very much for the help. Everything is clear now.
