### ISSUE TITLE
What if I have two columns as starting feature when generating data

### ISSUE THREAD

**Issue by coding-cadenza** [zhao-zilong/Tabula#5]
What if I have two columns as starting feature when generating data？

**Comment by zhao-zilong** [comment]
Hi @coding-cadenza  you can use tabula_sample function to given any starting prompts to generate the rest of data: https://github.com/zhao-zilong/Tabula/blob/7d434e11a8d5bdcd7e5d4ff35afe1d1b04f9533d/tabula/tabula.py#L234C9-L234C22

**Comment by coding-cadenza** [comment]
Is this promt formatted like this: "Sex is female, Age is 26"? or just like the paper, which only keeps the first feature name and does not need 'is'

**Comment by zhao-zilong** [comment]
Ah, I see your point, I think the docstring is wrong, you should follow the Tabula data format, should be "Sex female, Age 26". But to be honest, if you specify sex as categorical, it may encode the female as 0 during preprocessing, so if you give "Sex female, Age 26" maybe not work. You may need to give "Sex 0, Age 26" . Currently, since we do not output this information, you may need to output it yourself.

In this place:
https://github.com/zhao-zilong/Tabula/blob/7d434e11a8d5bdcd7e5d4ff35afe1d1b04f9533d/tabula/tabula.py#L84C47-L84C59

You can add some code like this to output the encoding:

```
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(data['name'])
le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print(le_name_mapping)
{'Tom': 0, 'Nick': 1, 'Kate': 2}
```
You need to adapt it to your implementation

**Comment by coding-cadenza** [comment]
Okay, I know what you mean, but the format "Sex 0, Age 26" is still not the same as the format of "Sex 0""26" in the paper

**Comment by zhao-zilong** [comment]
Oh, I didn't understand you correctly. You mean you will use the middle padding model? so for middle padding, you cannot change column order. So you can just put "Sex 0""26" as you mentioned, this is totally correct.

**Comment by zhao-zilong** [comment]
@coding-cadenza  ok, one more thing, if you use middle padding model. We did not encode the categorical column there, so you can just give "Sex female""26". We did not encode it because middle padding model already massively shortened token sequences .

**Comment by coding-cadenza** [comment]
Okay, I understand, thank you very much for your patience
